# k8s/postgres/postgres-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fraud-detection
type: Opaque
stringData:             # stringData = plain text (K8s encodes it)
  POSTGRES_DB: fraud_detection
  POSTGRES_USER: fraud_user
  POSTGRES_PASSWORD: fraud_pass_k8s_2024